oat-sa/extension-tao-proctoring

- views/templates/blocks/footer.tpl
- views/templates/blocks/header.tpl
corresponding story : https://oat-sa.atlassian.net/browse/TAO-1401
requires https://github.com/oat-sa/tao-core/pull/537
> fix templates by removing deprecated Layout functions

- controller/Delivery.php
- helpers/Delivery.php
- helpers/ReasonCategory.php
- model/implementation/DeliveryService.php
- views/js/controller/Delivery/monitoring.js
- views/js/helper/status.js
requires https://github.com/oat-sa/tao-core/pull/631
> Tao 1794 bulk action popup

- controller/Delivery.php
- helpers/Delivery.php
- model/implementation/DeliveryService.php
- views/js/controller/Delivery/monitoring.js
- views/js/helper/status.js
This will  temporarily disable reporting irregularities when test is finished.
The AC in the user story does not mention in which state this action should be available : https://oat-sa.atlassian.net/browse/TAO-1772
That may leave us a little time to fix this.
> implement reporting service

- model/implementation/DeliveryService.php
added timestamp to test session variable to enable multiple instance of same variables
> added timestamp to test session variable

- controller/Delivery.php
- controller/ProctoringModule.php
- controller/Reporting.php
- helpers/TestCenter.php
- model/implementation/DeliveryService.php
- views/js/controller/Reporting/index.js
- views/js/templates/reporting/datepicker.tpl
- views/js/templates/reporting/irregularities.tpl
Related to: https://oat-sa.atlassian.net/browse/TAO-1831
> Tao 1831 activity report

- model/implementation/DeliveryService.php
Related to: https://oat-sa.atlassian.net/browse/TAO-1972
Filter the list of available test takers by proctor
> DeliveryService: fix the getAvailableTestTakers method

- views/js/controller/Delivery/index.js
Related to: https://oat-sa.atlassian.net/browse/TAO-1966
Requires: https://github.com/oat-sa/tao-core/pull/665
> Delivery/index: does not count the 'all session' as a session

- views/js/controller/Delivery/index.js
- views/js/controller/Delivery/monitoring.js
Related to https://github.com/oat-sa/tao-core/pull/670
> refactored to be compatible with API

- helpers/TestCenterHelper.php
- model/AssessmentResultsService.php
The reporting was broken in the proctoring interface.
> Fix the wrong use of TestSessionService in the reporting helpers

- manifest.php
- scripts/update/Updater.php
increase version from `1.7.0` to `1.7.1`
> increase version from 1.7.0 to 1.7.1

- config/default/DeliveryExecutionState.conf.php
- manifest.php
- model/event/DeliveryExecutionExpired.php
- model/implementation/DeliveryExecutionStateService.php
- model/implementation/TestSessionService.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-2002
https://github.com/oat-sa/extension-tao-act/pull/187
> Tao 2002 termination of expired executions

- views/js/controller/Delivery/index.js
- views/js/controller/TestCenter/index.js
Remove the useless polling on index pages
> Remove polling

- model/implementation/DeliveryService.php
Related to: https://oat-sa.atlassian.net/browse/TAO-2535
Some quick optimizations on the DeliveryService about delivery executions
> Tao 2535 quick optimizations

- helpers/DeliveryHelper.php
Related to https://oat-sa.atlassian.net/browse/TAO-2556
> Added sorting for delivery list for proctor

- model/EligibilityService.php
https://oat-sa.atlassian.net/browse/TAO-2557
> Deliveries Assigned to Test Center Sorting

- helpers/DeliveryHelper.php
- manifest.php
- model/implementation/DeliveryService.php
- scripts/update/Updater.php
(by Proctor)
https://oat-sa.atlassian.net/browse/TAO-2555
> Sorting by last name for test takers in assignments to a delivery 

- manifest.php
- views/js/controller/DeliveryServer/awaiting.js
Related to: https://oat-sa.atlassian.net/browse/TAO-2585
Requires:
- https://github.com/oat-sa/tao-core/pull/837
- https://github.com/oat-sa/extension-tao-testqti/pull/469
> Reset the paused state when the test is authorized

- controller/Delivery.php
- controller/ProctoringModule.php
- model/monitorCache/implementation/DeliveryMonitoringService.php
- views/js/controller/Delivery/monitoring.js
Default sorting changed - now by date
> Changed initial sorting - now by date

- manifest.php
- scripts/update/Updater.php
- views/templates/Reporting/layout.tpl
- views/templates/Reporting/print_report.tpl
- views/templates/Reporting/print_rubric.tpl
- views/templates/layout.tpl
Add the js and feature check on the proctoring template.
Also remove modernizr as well.
requires https://github.com/oat-sa/tao-core/pull/853
> add js check and remove modernizr

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
all fields in the form are required
https://oat-sa.atlassian.net/browse/TAO-2696
> in bulkActionPopup was added option reasonRequired

- manifest.php
- model/EligibilityService.php
- scripts/update/Updater.php
@krampstudio and @ssipasseuth Could you just confirmed that this hotix is not against the idea of the feature ?
> hotfix in case properties is not defined

- controller/Delivery.php
- manifest.php
- scripts/update/Updater.php
Related to: https://oat-sa.atlassian.net/browse/TAO-2823
> Fix pauseAll issue on monitoring index page

- manifest.php
- scripts/update/Updater.php
- scripts/update/setAdvancedKVExecutionPersistenceService.php
- scripts/update/setKVExecutionPersistenceService.php
https://oat-sa.atlassian.net/browse/TAO-3119
required for https://github.com/oat-sa/extension-tao-delivery/pull/196
> Migration to KV storage with extra execution state support

- test/ProctorManagementServiceTest.php
Test will not be passed if it was failed at least once and test data was not deleted because of fail. Test data should be wiped before each test.
> Clean test data before each test

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
> Authorize and Pause columns ordering were fixed

- manifest.php
- model/implementation/DeliveryService.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-3411
> Safer method usage with KV storage implementation

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
https://oat-sa.atlassian.net/browse/TAO-3299
> Added message for the singular selection

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
Fixed delivery name output on delivery execution page
https://oat-sa.atlassian.net/browse/TAO-3435
> Test taker name was added to the bulk action popup

- manifest.php
- model/ProctorService.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
See: https://oat-sa.atlassian.net/browse/TAO-3904
depends on https://github.com/oat-sa/tao-core/pull/1219
> Changed The way how tags notification is rendred

- manifest.php
- model/implementation/DeliveryExecutionStateService.php
- scripts/install/SetupProctoringEventListeners.php
- scripts/update/Updater.php
depends on:
https://github.com/oat-sa/extension-tao-testqti/pull/796/files
https://github.com/oat-sa/extension-tao-test-runner-plugins/pull/4/files
> Tao 4136 log delivery execution pause

- manifest.php
- model/ActivityMonitoringService.php
- scripts/update/Updater.php
- views/templates/Tools/assessment_activity.tpl
To test it : 
* Install taoProctoring (of course)
* log in as an operational Administrator
* Go in the Assessment Activity screen (under the tools)
* See the different info boxes
> Tao 4237 user activity

- controller/DeliveryServer.php
- manifest.php
- scripts/update/Updater.php
- views/js/controller/DeliveryServer/awaiting.js
- views/templates/DeliveryServer/awaiting.tpl
https://oat-sa.atlassian.net/browse/TAO-4240
> Tao 4240/test taker authorization screen displays

- config/default/ActivityMonitoringService.conf.php
- controller/Tools.php
- manifest.php
- model/ActivityMonitoringService.php
- model/datatable/DeliveriesActivityDatatable.php
- scripts/update/Updater.php
- views/js/component/activityMonitoring/currentAssessmentActivity/currentAssessmentActivity.js
- views/js/component/activityMonitoring/currentAssessmentActivity/currentAssessmentActivity.tpl
- views/js/component/activityMonitoring/deliveriesList/deliveriesList.js
- views/js/component/activityMonitoring/userActivity/userActivity.js
- views/js/component/activityMonitoring/userActivity/userActivity.tpl
- views/js/controller/Tools/assessmentActivity.js
- views/templates/Tools/assessment_activity.tpl
[TAO-4236](https://oat-sa.atlassian.net/browse/TAO-4236)
> TAO-4236 Assessment Activity Auto Refresh

- scripts/update/Updater.php
> Fix of the fix.

- locales/en-US/eligibility.rdf.po
- manifest.php
- model/ProctorService.php
- model/authorization/TestTakerAuthorizationService.php
- scripts/install/proctoring.rdf
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-4483
> Added flag for activate proctoring on selected deliveries

- manifest.php
- model/execution/ProctoredSectionPauseService.php
- scripts/update/Updater.php
It looks like I've left debug comments in the [previous PR](https://github.com/oat-sa/extension-tao-proctoring/pull/480)
> remove debug comments

- manifest.php
- model/AssessmentResultsService.php
- scripts/update/Updater.php
depends on https://github.com/oat-sa/extension-tao-delivery-rdf/pull/133
> Tao 5533/fix kv execution compatibility

- manifest.php
- model/AssessmentResultsService.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
related to https://github.com/oat-sa/extension-tao-nccer-delivery/pull/373
> unactive printRubric

- config/default/ActivityMonitoringService.conf.php
- controller/Tools.php
- manifest.php
- model/ActivityMonitoringService.php
- scripts/update/Updater.php
- views/js/component/activityMonitoring/userActivity/userActivity.js
- views/js/component/activityMonitoring/userActivity/userActivity.tpl
- views/js/component/activityMonitoring/userActivity/userActivityBlock.tpl
- views/js/controller/Tools/assessmentActivity.js
https://oat-sa.atlassian.net/browse/TAO-5658
> Tao 5658/configurable operational metrics support

- controller/Tools.php
- helpers/DeliveryHelper.php
- manifest.php
- model/DeliveryExecutionStateService.php
- model/implementation/DeliveryExecutionStateService.php
- scripts/update/Updater.php
Add more info to detect which delivery has failing message
> Fix/tao 5781/add more info

- manifest.php
- model/deliveryLog/DeliveryLog.php
- model/deliveryLog/implementation/RdsDeliveryLogService.php
- model/monitorCache/DeliveryMonitoringService.php
- model/monitorCache/implementation/MonitoringStorage.php
- scripts/update/Updater.php
Depends:
https://github.com/oat-sa/extension-tao-delivery/pull/311
> Feature/tao 5824/delete delivery

- manifest.php
- model/ActivityMonitoringService.php
- scripts/update/Updater.php
depends on https://github.com/oat-sa/tao-core/pull/1617
> Tao 5822 move time keys to date helper

- manifest.php
- model/implementation/DeliveryExecutionStateService.php
- scripts/AbstractExpiredSessionSeeker.php
- scripts/TerminateNotStartedAssessment.php
- scripts/TerminatePausedAssessment.php
- scripts/update/Updater.php
related task:
https://oat-sa.atlassian.net/browse/TAO-5967
> TAO-5967 fix termination of expired sessions

- manifest.php
- model/monitorCache/implementation/MonitoringStorage.php
- scripts/install/db/DbSetup.php
- scripts/tools/KvMonitoringMigration.php
- scripts/update/Updater.php
Memory leak fixed
Allow script to continue from last iteration on re-run
> Useless column removed

- manifest.php
- model/import/ProctorCsvImporter.php
- scripts/install/SetupProctorCsvImporter.php
- scripts/update/Updater.php
Requires https://github.com/oat-sa/tao-core/pull/1687
> Feature/tao 5905/import user

- controller/Reporting.php
- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
1. Enable in config/taoProctoring/AssessmentResults.conf.php print_report_button by setting to true.
2. Pass a delivery execution.
3. Check the report on proctor monitoring execution script.
> Fix/tt 332/report generation

- manifest.php
- scripts/update/Updater.php
> Release 8.10.1

- manifest.php
- model/runner/ProctoringRunnerService.php
- scripts/update/Updater.php
**DEPENDS ON https://github.com/oat-sa/extension-tao-testqti/pull/1339**
> proper pause

- manifest.php
- scripts/update/Updater.php
- test/integration/deliveryLog/RdsDeliveryLogServiceTest.php
- test/integration/model/authorization/ProctorAuthorizationProviderTest.php
- test/integration/monitorCache/DeliveryMonitoringDataTest.php
- test/integration/monitorCache/DeliveryMonitoringServiceTest.php
- test/integration/monitorCache/MonitorCacheServiceTest.php
- test/integration/monitorCache/helpers/MonitorCacheServiceThread.php
- test/integration/monitorCache/mock/DeliveryMonitoringData.php
- test/unit/model/ActivityMonitoringServiceTest.php
According to https://oat-sa.atlassian.net/browse/TAO-6469
> Tao 6469 fix backend tests

- controller/ExecutionRestService.php
- doc/rest.json
- manifest.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-7015
> Tao 7015/rest controller for unstop

- manifest.php
- model/implementation/TestSessionHistoryService.php
- scripts/update/Updater.php
Depends on [taoLti PR 151](https://github.com/oat-sa/extension-tao-lti/pull/151)
> Fix/tao 7087/actor details missing when use kvstorage

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
https://oat-sa.atlassian.net/browse/TAO-6722
> date comparison fixed

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
Related to : https://oat-sa.atlassian.net/browse/TAO-7780
Enable control for selecting page size
- login as a Proctor user
- navigate to Monitor page
- try to change amount of items per page
Requires PR :
> [TAO-7780] Tutor - allow for additional candidates on proctor screen

- manifest.php
- scripts/update/Updater.php
Depends on https://github.com/oat-sa/extension-tao-delivery/pull/395
> Fixed if services not registered

- manifest.php
- scripts/update/Updater.php
Fix updater script to work after hotfixes.
> Hotfix/tao 7603/fix updater script

- manifest.php
- model/event/DeliveryExecutionFinished.php
- scripts/install/RegisterWebhookEvents.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-8497
Depends on: https://github.com/oat-sa/tao-core/pull/2235
Register DeliveryExecutionFinished event in webhooks service
> Register DeliveryExecutionFinished event in webhooks service

- manifest.php
- model/event/DeliveryExecutionFinished.php
- scripts/update/Updater.php
https://oat-sa.atlassian.net/browse/TAO-8498
Fix for changes in https://github.com/oat-sa/tao-core/pull/2247
> fix DeliveryExecutionFinished event for webhook support

- controller/DeliveryServer.php
- manifest.php
- model/implementation/TestSessionHistoryService.php
- scripts/TerminateNotStartedAssessment.php
- scripts/update/Updater.php
message added in database the language of the test taker
now the message add in database in the English  language
the language of the proctor is taken to create the story
relative https://github.com/oat-sa/extension-tao-test-runner-plugins/pull/132
> adding a message to the database in English

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
https://oat-sa.atlassian.net/browse/NCC-62
> Fix/ncc 62/accent character

- manifest.php
- model/authorization/TestTakerAuthorizationService.php
- scripts/update/Updater.php
- test/unit/model/authorization/TestTakerAuthorizationServiceTest.php
JIRA: https://oat-sa.atlassian.net/browse/TAO-9572
The goal of this PR is to make to make it possible to check from other services if test is in secure mode.
Small refactoring in isProctored method.
> Fix/tao 9572/refactor authorization service to allow extension

- manifest.php
- model/monitorCache/implementation/MonitoringStorage.php
- scripts/update/Updater.php
related to ncsup 261. Fix for mysql group_concat separator
> Fix/ncsup 261/mysql group concat

- manifest.php
- scripts/update/Updater.php
- test/integration/deliveryLog/RdsDeliveryLogServiceTest.php
- test/integration/model/authorization/ProctorAuthorizationProviderTest.php
- test/integration/monitorCache/DeliveryMonitoringDataTest.php
- test/integration/monitorCache/DeliveryMonitoringServiceTest.php
- test/integration/monitorCache/MonitorCacheServiceTest.php
- test/unit/model/authorization/TestTakerAuthorizationServiceTest.php
- test/unit/model/execution/DeliveryExecutionListTest.php
related to: https://oat-sa.atlassian.net/browse/TDR-1
depends on: https://github.com/oat-sa/generis/pull/751
Upgrade to phpunit8
> Feature/tdr 1/phpunit8 upgrade

- manifest.php
- scripts/tools/KvMonitoringMigration.php
- scripts/update/Updater.php
JIRA: https://oat-sa.atlassian.net/browse/ACTP-342 (not directly related)
Problem when total number of records in `delivery_monitoring` table is smaller that `$chunkSize` value there is infinite loop in while statement.
> Fix/actp 342/fix infinite loop issue in migration script

- manifest.php
- model/deliveryLog/event/DeliveryLogEvent.php
- model/implementation/DeliveryExecutionStateService.php
- model/service/IrregularityReport.php
- scripts/TerminatePausedAssessment.php
- scripts/update/Updater.php
JIRA ticket: https://oat-sa.atlassian.net/browse/TCA-560
Create constants for main delivery log event IDs values.
> Feature/tca 560/add event id constants

- helpers/DeliveryHelper.php
- manifest.php
- scripts/update/Updater.php
- views/js/component/timeHandling/timeHandling.js
- views/js/component/timeHandling/timeHandling.tpl
- views/js/controller/Delivery/monitoring.js
Related to : https://oat-sa.atlassian.net/browse/TCA-572
Added reasons for time adjustments actions.
- Open time adjustment popup, and new fields will be there (category, sub-category and commentary)
- This data will be passed to server with request (we can see it in the debug-bar of browser in the network tab)
> Feature/tca 572/irr for time adjustments

- manifest.php
- scripts/update/Updater.php
- views/templates/layout.tpl
https://oat-sa.atlassian.net/browse/TCA-554
"Header" landmark should not have a heading, the footer is currently missing a label.
1. Go to the Proctoring page
2. Check that:
- `<header>` tag has `aria-label=”Main Menu”`
> Fix/tca 554/refactor header and footer

- manifest.php
- model/execution/DeliveryExecutionManagerService.php
- scripts/update/Updater.php
JIRA: https://oat-sa.atlassian.net/browse/TCA-607
Small refactoring to make it possible to extend/modify functinality implemented in https://github.com/oat-sa/extension-tao-proctoring/pull/822
> Fix/tca 607/catch exception from external library

- model/execution/DeliveryExecutionManagerService.php
- test/unit/model/execution/DeliveryExecutionListTest.php
- test/unit/model/execution/DeliveryExecutionManagerServiceTest.php
fixed issue:
Please test it with Unit tests
> Fixed null pointer

- manifest.php
- scripts/update/Updater.php
- test/unit/model/execution/DeliveryExecutionListTest.php
- test/unit/model/execution/DeliveryExecutionManagerServiceTest.php
JIRA ticket: https://oat-sa.atlassian.net/browse/TCA-579
Fixed failing unit tests.
Small refactoring of DeliveryExecutionManagerServiceTest.php
> Fix/tca 579/fix unit tests

- manifest.php
- scripts/update/Updater.php
- views/js/component/timeHandling/timeHandling.js
- views/js/controller/Delivery/monitoring.js
https://oat-sa.atlassian.net/browse/TCA-573
Proctors must have ability  to acquire more useful error messages and time handling form validation.
- Open somу test sessions via LTI
- Pause it from proctor side and atry to increase-decrease time for testtakers
- Check if time limit conditions are respected and error messages shown
none
> Feature/tca 573/change time errors handling

- manifest.php
- test/unit/model/execution/DeliveryExecutionManagerServiceTest.php
Fixed risky unit tests without assertions.
> Fix/tca 573/fix failing unit tests

- controller/DeliveryServer.php
- manifest.php
- model/DeliveryServerService.php
- test/unit/model/execution/DeliveryServerServiceTest.php
https://oat-sa.atlassian.net/browse/NCC-204
How to test:
1. Run a test with the proctoring mode.
2. Pass a few items.
3. Press the logout button 
4. Check the session by a proctor. It's should be the paused session
> Fix/ncc 204/pause sessions

- manifest.php
- views/js/controller/Delivery/monitoring.js
Related to : https://oat-sa.atlassian.net/browse/PR-157
After you perform a function (terminate, add time, refresh page), the checkbox is no longer checked.
- check delivery(s)
- press refresh button
- checkboxes still checked
After refresh button clicked - checkboxes should be cleaned
> PR-157. Proctoring page. Checkboxes

- model/GuiSettingsService.php
Related to: https://oat-sa.atlassian.net/browse/PR-346
> doc: Added note to the auto refresh const to aware of to low refresh rate

- model/GuiSettingsService.php
> Release 20.0.4

- scripts/install/SetupProctoringEventListeners.php
- scripts/tools/MonitoringExtraFieldConfigurationMigration.php
> fix: do not catch catchSessionPause by MonitoringListener

- views/scss/proctoring.scss
**related to:** https://oat-sa.atlassian.net/browse/PR-622
**Description:** Added `nowrap` to monitoring table.
Before:
After:
> Fix/pr 622/monitoring table wrap

- manifest.php
- views/scss/proctoring.scss
**Related to:** https://oat-sa.atlassian.net/browse/PR-622
Backport of https://github.com/oat-sa/extension-tao-proctoring/pull/901 to TAO sprint 143.
> Backport/pr 622/monitoring table wrap

- composer.json
> Release 20.1.3

- model/authorization/TestTakerAuthorizationService.php
> Release 20.2.2

- config/default/MonitoringListener.conf.php
- migrations/Version202106081338544101_taoProctoring.php
- model/datatable/DeliveriesActivityDatatable.php
- model/listener/MonitoringListener.php
- model/listener/MonitoringListenerInterface.php
- model/monitorCache/DeliveryMonitoringService.php
- model/monitorCache/implementation/MonitoringStorage.php
- model/repository/MonitoringRepository.php
- scripts/install/SetupDeliveryMonitoring.php
- scripts/install/SetupProctoringEventListeners.php
- scripts/install/db/DbSetup.php
- scripts/tools/KvMonitoringMigration.php
- scripts/tools/MonitoringExtraFieldConfigurationMigration.php
- scripts/tools/MonitoringExtraFieldMigration.php
- test/unit/model/DeliveryMonitoringStorageTest.php
- test/unit/model/listener/MonitoringListenerTest.php
> Release 20.3.0

- model/repository/MonitoringRepository.php
> Release 20.4.1

- manifest.php
> Release 20.4.2

- config/default/DeliveryExecutionList.conf.php
- helpers/DeliveryHelper.php
- migrations/Version202203141404254101_taoProctoring.php
- model/datatable/DeliveriesMonitorDatatable.php
- model/execution/DeliveryExecutionList.php
- model/execution/DeliveryExecutionListInterface.php
https://oat-sa.atlassian.net/browse/OATSD-1664
> fix: Examination title in proctor console

- config/default/DeliveryExecutionList.conf.php
- helpers/DeliveryHelper.php
- migrations/Version202203141404254101_taoProctoring.php
- model/datatable/DeliveriesMonitorDatatable.php
- model/execution/DeliveryExecutionList.php
- model/execution/DeliveryExecutionListInterface.php
> Release 20.5.0

- config/default/DeliveryExecutionList.conf.php
- helpers/DeliveryHelper.php
- manifest.php
- migrations/Version202203141404254101_taoProctoring.php
- model/datatable/DeliveriesMonitorDatatable.php
- model/execution/DeliveryExecutionList.php
- model/execution/DeliveryExecutionListInterface.php
backport of https://github.com/oat-sa/extension-tao-proctoring/pull/923
> Backport/oatsd 1664/proctor monitor delivery label

- model/repository/MonitoringRepository.php
How to reproduce:
- configure env for the DEPP reality
- start lti delivery 
- receive 500
- restart the page
After the fix is applied - 500 error on lti launch would be gone
> Fix/lsi 1089/fix 500 on lti start

- model/repository/MonitoringRepository.php
> Release 20.5.3

- locales/de-DE/proctoring.rdf.po
- locales/es-ES/proctoring.rdf.po
- migrations/Version202309291445224101_taoProctoring.php
Rdf export/import from neo4j
- fix: removed duplicated translations and fixed typo.
> REL-1197: Rdf export/import from neo4j

- composer.json
- views/js/component/activityMonitoring/currentAssessmentActivity/currentAssessmentActivity.js
- views/js/controller/Delivery/index.js
- views/js/controller/Delivery/monitoring.js
Related: https://oat-sa.atlassian.net/browse/ADF-1579
Update lodash methods to version 4. 
Documentation: https://github.com/lodash/lodash/wiki/Migrating
> chore: update methods to lodash 4 verios
