- controller/DeliveryServer.php
- model/implementation/DeliveryService.php
Related to: https://oat-sa.atlassian.net/browse/TAO-1918
Add session stored values to check if the proctor authorization is valid for the current test taker's HTTP session.
If the test taker refreshes the page, he/she can continue to process the assessment. But if he/she logs off, or goes to the index page, he/she will have to wait for proctor authorization when trying to process the delivery again, even if the delivery has already been authorized and is in progress.
Without this patch, when the delivery is authorized, the test taker can can log off and log in, and then access the delivery without waiting for proctor authorization. The test taker can also return to the index page, and still process the delivery without proctor re-authorization.
> Tao 1918 proctor authorization is required

- controller/TestCenterManager.php
- model/ProctorManagementService.php
- model/TestCenterService.php
- views/templates/layout.tpl
This will connect the test center listing to the new authorized proctor property.
With this we can test the whole workflow, so this should allow :
* ACT admin (backoffice) create a test center, assign test center admin and proctors
* test site admin can access proctor management screen and see the assigned proctors
* test site admin can authorize/unauthorize the assigned proctors
* authorized proctor can now see their test center
* test site admin can create new proctor and the new proctor is visible among the assigned proctors tree in the ACT admin interface
> using new assigned proctor properties

- helpers/TestCenterHelper.php
Let some delivery executions opened/awaiting 
As a proctor, open the Activity report GUI and filter with a date in the future, all unterminated deliveries will stay listed.
The PR should fix that.
> apply the filtering also on executions without an end time

- model/monitorCache/implementation/DeliveryMonitoringData.php
Related to: https://oat-sa.atlassian.net/browse/TAO-2694
Build the assessment progress status from the current position inside the section rather than the position inside the whole test.
> Use the position in the section instead of the whole test

- views/templates/form_test_center.tpl
If `Assign proctors` tree higher than `Define sub-centers`  tree then markup breaks down:
> Move grid to separate container

- model/authorization/ProctorDeliveryAuthorizationService.php
- remove a test center with active executions, then try to connect with a test takers who was assigned to the execution.
> prevent checking testcenter for ghost execs

- views/js/controller/Delivery/index.js
Related to: https://oat-sa.atlassian.net/browse/TAO-2823
Requires: https://github.com/oat-sa/extension-tao-proctoring/pull/180
When trying to pause sessions from the monitoring index, if an error occurs the displayed message contains "undefined".
To easily reproduce the issue you need some unrecoverable blocked delivery executions. Otherwise you can fake an error in the controller: https://github.com/oat-sa/extension-tao-proctoring/blob/develop/controller/Delivery.php#L487
Added some refactoring to comply to ESLint rules.
> Fix the undefined error message

- manifest.php
- scripts/TerminatePausedAssessment.php
- scripts/update/Updater.php
Reason should be the same as proctor events have (in accordance with ODS documentation).
> change reason for terminated assessments

- config/default/DeliveryMonitoring.conf.php
- manifest.php
- model/monitorCache/implementation/DeliveryMonitoringService.php
- scripts/update/Updater.php
I found that getting schema takes very long time. After this change I got significant accelerations for such requests as heartbeat, move (next, prev, skip), submitting item data and other requests where delivery monitoring storage is used. 
For example I got 50% acceleration for heartbeat call (189ms vs 361ms).
> use select request instead of fetching schema

- controller/DeliveryServer.php
- manifest.php
- scripts/update/Updater.php
During initialization of delivery execution it's state is set to `active`
https://github.com/oat-sa/extension-tao-delivery/blob/master/models/classes/execution/class.OntologyService.php#L104
and before it's state changed to `awaiting` active executions pauses here:
https://github.com/oat-sa/extension-tao-proctoring/blob/master/controller/DeliveryServer.php#L110
It causes redundant pause event in the ODS before the first proctor's authorization.
> pause delivery execution after initialization

- scripts/update/Updater.php
Some of the servers have version 3.16.1 installed, that lead to update failure
> missing version should be taken into account

- manifest.php
- scripts/install/SetUpProctoringUrlService.php
- scripts/update/Updater.php
Create assessors to access configurable routes to make easier to override it
Requires https://github.com/oat-sa/tao-core/pull/1322
> Use set/get route to access urlservice options

- manifest.php
- scripts/update/Updater.php
- test/unit/model/ActivityMonitoringServiceTest.php
Basically, the test was asserting that the number of days in the month of today equals the number of days of the month of tomorrow, which should fail on last day of every month (except 31 of July, obviously).
Still, this fixes the test but not the code. I'm not sure what the goal of the code is: when requesting for timekeys for the month, (e.g. March has 31 days), we get timekeys from 1st of march and 31 days back, to january 30...
The count of days is good (31), but we don't cover the february month...
Note:
```cal_days_in_month(CAL_GREGORIAN, $date->format('m'), $date->format('Y'))```
can be advantageously replaced with
```$date->format('t')```
> Fixed failing nightly build test

- manifest.php
- model/monitorCache/DeliveryMonitoringData.php
- model/monitorCache/implementation/DeliveryMonitoringData.php
- scripts/update/Updater.php
- test/integration/monitorCache/DeliveryMonitoringDataTest.php
- test/integration/monitorCache/mock/DeliveryMonitoringData.php
Store delivery execution context data in delivery monitoring data.
Requires: 
https://github.com/oat-sa/extension-tao-delivery/pull/385
https://github.com/oat-sa/extension-tao-lti/pull/174
> Feature/tao 7389/extend monitoring data with execution context

- manifest.php
- scripts/install/RegisterDeleteDeliveryExecution.php
- scripts/update/Updater.php
When taoProctoring installed `DeliveryMonitoring` storage is not registered in `taoDelivery/DeliveryExecutionDelete` service.
steps to reproduce:
1. install tao and taoProctoring extension
2. finish one test
3. try to delete delivery. `DeliveryDeleteTask` will add itself to the queue again and again because delivery execution is not deleted from `DeliveryMonitoring` storage
> registrer DeliveryMonitoring storage in DeliveryExecutionDeleteService

- manifest.php
- scripts/update/Updater.php
- views/js/controller/DeliveryServer/awaiting.js
https://oat-sa.atlassian.net/browse/TAO-7852
On the test launching with lti tool - clipboard is clean (has space instead of any content)
Improvement (now it works with iPad)
> clipboard cleaner improved (now it works with ipad)

- manifest.php
- model/implementation/TestSessionHistoryService.php
- scripts/update/Updater.php
Issue: https://oat-sa.atlassian.net/browse/TAO-8581
Issue should be fixed by this PR https://github.com/oat-sa/extension-lti-proctoring/pull/120.
The goal of this modification is to do not use `Test Taker` role by default for all events which were not performed by proctor.
To test: 
1. Start delivery execution via LTI.
2. Pause execution from proctor screen.
3. Terminate execution using CLI action `taoProctoring/scripts/TerminatePausedAssessment.php`
4. Go to proctor screen and try to open detailed view for terminated session
> Do not use test taker role by default

- manifest.php
- scripts/update/Updater.php
- test/unit/model/ActivityMonitoringServiceTest.php
When trying to increment DateTime for 1 second, 1 hour or 1 day, cast the new value to:
- 00-59 for seconds
- 00-23 for hours
- 01-12 for months (modulo before increment to get 1 based)
> Fixed test for time keys increment casted to regular number of seconds, hours or months.

- manifest.php
- model/GuiSettingsService.php
- scripts/install/RegisterGuiSettingsService.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
Related to: https://oat-sa.atlassian.net/browse/TAO-9100
Added option setStartDataOneDay to GuiSettingsService.
By default setStartDataOneDay=true and filter will be set on data range of one day
Added handler on `clean` event, to apply datatable filter
Related to https://github.com/oat-sa/extension-tao-depp/pull/186
> Fix/tao 9100/add option setStartDataOneDay and filter table bu clean start data

- manifest.php
- model/authorization/TestTakerAuthorizationService.php
- scripts/update/Updater.php
- test/unit/model/authorization/TestTakerAuthorizationServiceTest.php
Related with: https://oat-sa.atlassian.net/browse/TAO-9572
Steps to reproduce:
1 Create proctored and not secure delivery 
2 Log in as a test taker and run delivery
3 Activate test taker session as proctor
4 Start test as test taker and in any step refresh page
The same steps  for lti run
Expected result: test-taker able to continue test
Actual result: test-taker session become paused and request a proctor activation again
> add ACTIVE delivery execution state to state check

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
Related to: https://oat-sa.atlassian.net/browse/TAO-9995
When proctor trying to update different statuses in one request it causes an error.
- Prepare at least two test-takers and create proctored test delivery.
- Log in as a proctor and authorize one session to prepare a list of sessions with different statuses.
- Click on checkboxes to select all users (authorized and non-authorized)
- Click the "Authorize" button on top of the data grid toolbar.
- Confirm Bulk operation in the popup.
- The bulk operation will return "Oops, something went wrong" error for not a fixed environment
All steps are equal to the previous section, but on a fixed environment bulk action will return the success message.
> TAO-9995 fix error on bulk operations on proctor screen

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
Related to : https://oat-sa.atlassian.net/browse/ACTP-221
added allow_irr page parameter - that can disable irregularities feature for proctor
pageParams.allowIrr parameter can hide Report Irregularities from the GUI
Companion PR :
> allow irr page parameter

- manifest.php
- model/execution/DeliveryExecutionList.php
- model/monitorCache/DeliveryMonitoringService.php
- scripts/update/Updater.php
Make remaining time on proctor screen more accurate after pause event.
Related to : https://oat-sa.atlassian.net/browse/ACTP-245
This PR adds an additional value stored in delivery monitoring cache, to track the time that was already stored in timer duration storage.
Steps to reproduce the initial bug and how to test is described in companion PR: https://github.com/oat-sa/extension-tao-act/pull/1295
Companion :
> Feature/actp 245/proctor remaining time

- manifest.php
- model/authorization/TestTakerAuthorizationService.php
- scripts/update/Updater.php
- test/unit/model/authorization/TestTakerAuthorizationServiceTest.php
Should be merged after https://github.com/oat-sa/extension-lti-proctoring/pull/128
JIRA: https://oat-sa.atlassian.net/browse/ACTP-282
The goal of this PR is to change logic how do we check if delivery execution is in secure mode. Only `blurPause` plugin should be used to check if delivery execution should be paused when focus is lost in test runner. This plugin may be included in multiple features. 
With the new implementation we will get list of enabled plugins from DeliveryContainerService (which will handle LTI parameters for available test runner features as well) and decide if test taker is authorized to resume the test.
> Feature/actp 282/decide if delivery is secure based on plugin

- manifest.php
- scripts/update/Updater.php
- views/js/controller/Delivery/monitoring.js
Related to : https://oat-sa.atlassian.net/browse/ACTP-383
When the new allow_irr parameter is false, a buttonless pop up box comes up when a test was completed or terminated. 
- run lti proctoring with optional parameter `allow_irr=false`
- click on the `terminate/reactivate or irregularity button` of the delivery that was terminated or finished
- there is no buttons in the dialog
- run lti proctoring with optional parameter `allow_irr=false`
- button `terminate/reactivate or irregularity button` should be disabled for the delivery executions that was finished or terminated
> Fix/actp 383/avoid empty irregularity dialog

- manifest.php
- scripts/update/Updater.php
- views/js/templates/deliveryServer/authorizationEntryPoint.tpl
**Related to:**
https://oat-sa.atlassian.net/browse/ACTP-415
**Description:**
The card on Proctoring page has it's own tab stop. This does not make sense.
**How to check:**
Login as test taker and start some test with proctoring enabled.
The card on Proctoring page: `<div class="block entry-point …">` should not have `tabindex="0"`.
> Fix/actp 415/card announcement proctoring page

- manifest.php
- model/monitorCache/implementation/MonitoringStorage.php
- scripts/update/Updater.php
Related to tasks: 
NCC-185, ACTP-342
Description: 
This recent PR- https://github.com/oat-sa/extension-tao-proctoring/pull/793 has introduced an error when using PostgreSQL:
```
SQLSTATE[42803]: Grouping error: 7 ERROR: column "t.delivery_execution_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT delivery_execution_id,
```
This PR forces the column `delivery_execution_id` to always be added to `GROUP BY`, once there's at least one column passed on the `GROUP BY`.
> Fix/ncc 185/fix group by in psql

- controller/DeliveryServer.php
- manifest.php
- scripts/update/Updater.php
Related to : https://oat-sa.atlassian.net/browse/TCA-341
Default title for authorization page
Check pages:
• delivery authoring: TAO: User Authorization
Requires:
> default title of the authorization page

- manifest.php
- scripts/update/Updater.php
- views/templates/DeliveryServer/awaiting.tpl
**Related**
https://oat-sa.atlassian.net/browse/TCA-414
**Description**
A11y issues on the Proctoring page
**How to test:**
1. Create delivery with the proctoring screen
2. Reach the proctoring screen as a test tacker
3. Ensure that `<div class="section-container">` has the `role="main"` and `aria-label="Proctor authorization”`
4. Ensure that it is correctly announced by the screen reader
> Fix/tca 414/a11y layout

- manifest.php
- model/implementation/DeliveryExecutionStateService.php
- scripts/update/Updater.php
- [TBD-33](https://oat-sa.atlassian.net/browse/TBD-33) fix: apply custom delivery execution session manipulations after setting a delivery execution state so that they're applied last
- [TBD-33](https://oat-sa.atlassian.net/browse/TBD-33) chore(version): bump a fix one
> Fix TBD-33: impossible to resume a timed out delivery execution

- manifest.php
- scripts/install/db/DbSetup.php
- scripts/update/Updater.php
Moving several columns from `kv_delivery_monitoring` to `delivery_monitoring` table.
Related to : https://oat-sa.atlassian.net/browse/TCA-647
No changes in the UI or in behavior in tao community edition.
> Fix/tca 647/remaining time mismatch

- manifest.php
- model/execution/DeliveryExecutionList.php
- test/unit/model/execution/DeliveryExecutionListTest.php
Related to : https://oat-sa.atlassian.net/browse/TCA-600
The pre-population shall only occur if it c"n be "etermined t"at the"proctor almost certainly clicked on “Pause” (i.e. the “paused” session of the TT has been initiated by the Proctor and NOT by the TT losing focus)
How to test:
1. In the DE with secure mode press ESC and there will be an pause action, check that proctor doesn't see reasons when clicks on the adjustment time button
2. When proctor pauses DE by himself - then pre-populated data should be filled for the adjustment time action
> Fix/tca 600/avoid system pause reason prepopulation

- manifest.php
- views/js/controller/DeliveryServer/awaiting.js
Related to: https://oat-sa.atlassian.net/browse/TCA-707
- Launch a test as test-taker.
- Authorize the test as proctor.
- On 'awaiting authorization' screen, make sure that proceed button is enabled.
- Terminate the test as proctor.
- Notice that there is no termination message presented to the test taker.
- Test taker can click on 'Proceed' and is taken to a blank page that has "My tests"  heading.
- Test taker is on awaiting authorization page (with Proceed button enabled) and proctor terminates the test
- When TT clicks on Proceed the system performs a last check and to displays a warning dialog to inform clearly on the issue  (notify about the test termination). 
- Then, only after the TT acknowledged what happened and click on “ok”, the TT is redirected to the …
> Fix/tca 707/dialog on terminated session

- manifest.php
- model/execution/DeliveryExecutionManagerService.php
- test/unit/model/execution/DeliveryExecutionManagerServiceTest.php
JIRA ticket: https://oat-sa.atlassian.net/browse/TCA-573
Problem:
- timer adjustment is allowed for delivery executions without timer.
How to test:
- create and start two delivery executions, one with timer and one without
- authorize -> start -> pause both delivery executions
- check on proctor screen that time adjustment button is active only for delivery execution with timer (only "Delivery of SAMPLEMATH_B1 test" on the screen has a timer).
> Fix/tca 573/allow time adjustment only for deliveries with timer

- manifest.php
- model/monitorCache/implementation/MonitorCacheService.php
- test/unit/model/execution/DeliveryExecutionManagerServiceTest.php
JIRA ticket: https://oat-sa.atlassian.net/browse/TCA-725
Problem: when terminated test session is reactivated it shows incorrect test position `finished - item /` and empty remaining time.
Solution: test session reactivation triggers event `QtiTestStateChangeEvent`. Update test position and remaining time in delivery monitoring to represent real test session state.
How to test:
- start delivery execution 
- terminate delivery execution
- reactivate delivery execution (requires both `TeachingAssistant` and `Administrator` roles for proctor user)
- check that on proctor screen there are correct data in `Progress` and `Remaining` columns
> Fix/tca 725/update test position and remaining time on reactivation

- manifest.php
- views/js/component/timeHandling/timeHandling.js
Relates to: [BSA-269](https://oat-sa.atlassian.net/browse/BSA-269)
**Changes:** do not show error if time adjustment increase limit setted to -1.
**How to test:**
1. create the delivery with timed section(s);
2. execute the delivery via TT and pause it via Proctor;
3. refresh the page via Proctor and add Extra Time value which will be greater than consumed time (e.g. if timer was setted to 10 minutes and it was paused on 9:00 - consumed time is 1 minute. So you need to add Extra Time more than 1 minute).
_Previous behaviour: **error message.**_
_Current behaviour: **no error message, extra time has no limits.**_
**Companion PR:** [#74](https://github.com/oat-sa/extension-tao-bosa-selor/pull/74)
> Fix/BSA-269/Extra Time limit error message

- manifest.php
- migrations/Version202011121023284101_taoProctoring.php
- model/listener/DeliveryExecutionStateListener.php
- test/unit/model/listener/DeliveryExecutionStateListenerTest.php
JIRA ticket: https://oat-sa.atlassian.net/browse/PR-28
Problem:
When proctor pauses a delivery execution remaining time shows value calculated based on last information from client test runner. It may cause some confusion when remaining time values becomes bigger, in some cases might be few minutes difference. 
To improve proctor user experience we can recalculate remaining time based on server timer. Later, when client test runner confirms pause event, remaining time will be recalculated based on test session timer and will contain the same remaining time as in test session.
How to test:
- (TT) start proctored delivery execution
- (proctor) authorize delivery execution
- (TT) wait for some time (at least 20-30 seconds)
- (proctor) pause delivery execution
- (TT) wait for next message …
> Feature/pr 28/update remaining time on proctor pause

- manifest.php
- views/js/controller/Delivery/monitoring.js
- views/js/helper/status.js
**Related to:**
https://oat-sa.atlassian.net/browse/PR-90
https://oat-sa.atlassian.net/browse/PR-89
https://oat-sa.atlassian.net/browse/PR-88
**Description:**
The three issues were related with permissions configuration for the _Completed_ and _Terminated_ statuses. Also for PR-89 I included the possibility of managing statuses permissions with functions and not just boolean values, so I had to make a small refactor of the `canDo` function, which now receives the full delivery and not only the state, so different properties of it can be used to check permissions. Regarding PR-90 there was a bug that was causing to request to the server to update the timer for both, the allowed and the denied resources, when multiple sessions were selected.
**Environment:** …
> Fix/pr 89/hide extra time button when unrequired

- manifest.php
- views/js/controller/Delivery/monitoring.js
- views/js/helper/status.js
**Related to:** 
https://oat-sa.atlassian.net/browse/PR-90
https://oat-sa.atlassian.net/browse/PR-89
**See also:** https://github.com/oat-sa/extension-tao-proctoring/pull/861
**Description:** 
This PR fixes two problems noticed on QA phase:
-  Some statuses had to update the permission for adding extra time to a session.
- An error caused by refactor made on https://github.com/oat-sa/extension-tao-proctoring/pull/861 that was causing not to show the denied reason when trying to make a forbidden action on the bulk action modal.
**before:**
**now:**
> Fix/pr 89/include reason on rejected bulk time updates

- manifest.php
- model/execution/DeliveryExecutionList.php
- views/js/controller/Delivery/monitoring.js
Related to: https://oat-sa.atlassian.net/browse/PR-142
- datetime-range replaced with date-rage as proctoring never worked with H:s (it was added by mistake when new datetime picker was added) [here](https://github.com/oat-sa/extension-tao-proctoring/pull/866/files#diff-92ee372f909de10dcd3ebee0c4539e6f9bcf7acb9ef00aca5bedbc930ba7002aR961)
- Deleted time adjustment error log, for the test sessions that can’t use it (thousands records in the log, that we don’t need) [here](https://github.com/oat-sa/extension-tao-proctoring/pull/866/files#diff-ef33637e6c90a7eda0155ee4cca8ac1f1e0b3f660cc7812e4db2dedb2c68c2bbR111)
- Issue with localization of the datetime picker, it should be initialized with datepicker component, not manually …
> Fix/pr 142/proctoring start date filter

- manifest.php
- views/js/controller/Delivery/monitoring.js
Related to: https://oat-sa.atlassian.net/browse/PR-142
Default date range should not be updated to default value on the datatable refresh action.
- Chose date range different then default
- Datatable reloads the data automatically with default date range
- Chose date range different then default
- Datatable shows us the correct data
> fix: datePicker value should be saved on the datatable refresh action

- manifest.php
- views/js/controller/Delivery/monitoring.js
Related to: https://oat-sa.atlassian.net/browse/PR-157
Summary:On the Proctor Console, when you select a test by clicking the checkbox next to it-- it remains checked even after you've terminated it, added time to it, refreshed the console, etc.
Actual Results:After you perform a function (terminate, add time, refresh page), the checkbox remains checked.
Expected Results:Currently, on Prod, after you perform a function (terminate, add time, refresh page), the checkbox is no longer checked. 
Steps to Reproduce:
Log into Pre-Prod as an Instructor/Proctor (I used Don Whyte Test - 28745).
Go to Child Org (I used Rock 'n' Roll High School).
Select Proctor Console.
Check the checkbox next to a test in progress.
Terminate the test.
The checkbox will remain checked even after …
> fix: checkboxes should be pured after the action success completion

- manifest.php
- views/js/controller/Delivery/monitoring.js
**Related to:** https://oat-sa.atlassian.net/browse/PR-190
**Description**
TT names with special characters (eg.: _ë, û, €, é_) are not being correctly rendered. Strings are originally received wrongly decoded from BE, so now they are directly parsed once datatable component notifies the new dataset. To do so jQuery `html` method is used to decode the string into a temporary div element (that is never appended to document) and then its content is extracted with jQuery `text`.
> fix(monitoring): fix display of tt names with special characters

- manifest.php
- views/js/controller/Delivery/index.js
**Related to:** https://oat-sa.atlassian.net/browse/PR-191
**Description:** The error was caused by the changes introduced long ago on [this PR](https://github.com/oat-sa/extension-tao-proctoring/pull/41/files) due to [this](https://oat-sa.atlassian.net/browse/TAO-1966) ticket. At some point in the past the _All sessions_ box was removed but this code was not, causing current issue.
> Fix/pr 191/fix available sessions counter

- model/implementation/TestSessionService.php
- test/unit/model/execution/DeliveryExecutionManagerServiceTest.php
- test/unit/model/execution/implementation/TestSessionServiceTest.php
Fixed QTI duration class name in tests and phpdoc.
No functionality change.
> fix: Fixed QTI duration class name.

- manifest.php
- migrations/Version202106081338544101_taoProctoring.php
- model/datatable/DeliveriesActivityDatatable.php
- model/monitorCache/implementation/MonitorCacheService.php
- model/monitorCache/implementation/MonitoringStorage.php
- model/monitorCache/implementation/SimpleMonitoringStorage.php
- scripts/install/db/DbSetup.php
Ticket : https://oat-sa.atlassian.net/browse/PR-471
/!\ Should not be merged. This PR is just to validate the change, then version will be created from this branch.
**Description**
In order to spare sql queries it has been decided to move  kv_delivery_monitoring to delivery_monitoring column called `extra_data`. For Mysql the type is `json` and for postgres it is `jsonb`.
This task consists in a minimal effort to avoid to refactor whole proctoring. To achieve it, MonitoringStorage class has been copied to SimpleMonitoringStorage to reproduce the behavior and alter only sql queries
The code includes a script to install new column. But migration are not part of this task
**Tested**
- Tested with sprint 134 (taoProctoring: 19.18.5)
- Tested with postgres, requires a new column `alter table …
> Feature/pr 471/improve sql performance

- config/default/MonitoringListener.conf.php
- migrations/Version202106081338544101_taoProctoring.php
- model/datatable/DeliveriesActivityDatatable.php
- model/listener/MonitoringListener.php
- model/listener/MonitoringListenerInterface.php
- model/monitorCache/DeliveryMonitoringService.php
- model/monitorCache/implementation/MonitorCacheService.php
- model/monitorCache/implementation/MonitoringStorage.php
- model/monitorCache/implementation/SimpleMonitoringStorage.php
- model/repository/MonitoringRepository.php
- scripts/install/SetupDeliveryMonitoring.php
- scripts/install/SetupProctoringEventListeners.php
- scripts/install/db/DbSetup.php
- scripts/tools/KvMonitoringMigration.php
- scripts/tools/MonitoringExtraFieldConfigurationMigration.php
- scripts/tools/MonitoringExtraFieldMigration.php
- test/unit/model/DeliveryMonitoringStorageTest.php
- test/unit/model/listener/MonitoringListenerTest.php
**Ticket**
https://oat-sa.atlassian.net/browse/PR-520
**Description**
This PR aims to transcript proctoring improvements to latest version with possibility to configure. 
it includes:
- [Refactor to improve database access](https://oat-sa.atlassian.net/browse/PR-471) (https://github.com/oat-sa/extension-tao-proctoring/pull/892)
- [Script to migrate data](https://oat-sa.atlassian.net/browse/PR-495) ()
- [Script to update to new impl](https://oat-sa.atlassian.net/browse/PR-495) (https://github.com/oat-sa/extension-tao-proctoring/pull/895)
Also event listeners have been moved from DeliveryService to a new MonitoringListener.
**To test**
All these scenarios should be run with psql and mysql.
- Checkout this PR, install the plaftorm with this PR, pass a proctored DX
- Do not checkout this PR, …
> Feature/pr 520/remove kv table

- model/authorization/TestTakerAuthorizationService.php
Extracted proctor authorization check to an overridable method
Related to : https://oat-sa.atlassian.net/browse/TR-2736
Behavior does not change.
Companion PR :
> chore: allow proctor authorization check override

- config/default/MonitoringListener.conf.php
- migrations/Version202106081338544101_taoProctoring.php
- model/datatable/DeliveriesActivityDatatable.php
- model/listener/MonitoringListener.php
- model/listener/MonitoringListenerInterface.php
- model/monitorCache/DeliveryMonitoringService.php
- model/monitorCache/implementation/MonitorCacheService.php
- model/monitorCache/implementation/MonitoringStorage.php
- model/monitorCache/implementation/SimpleMonitoringStorage.php
- model/repository/MonitoringRepository.php
- scripts/install/SetupDeliveryMonitoring.php
- scripts/install/SetupProctoringEventListeners.php
- scripts/install/db/DbSetup.php
- scripts/tools/MonitoringExtraFieldConfigurationMigration.php
- scripts/tools/MonitoringExtraFieldMigration.php
- test/unit/model/DeliveryMonitoringStorageTest.php
- test/unit/model/listener/MonitoringListenerTest.php
This forward ports:
- [v19.18.5.2](https://github.com/oat-sa/extension-tao-proctoring/releases/tag/v19.18.5.2)
- [v19.18.5.1](https://github.com/oat-sa/extension-tao-proctoring/releases/tag/v19.18.5.1)
- https://github.com/oat-sa/extension-tao-proctoring/pull/896
This is also available as [v19.20.7.2](https://github.com/oat-sa/extension-tao-proctoring/releases/tag/v19.20.7.2).
1. Set up `develop` version of the extension
2. Run a few proctored delivery executions and monitoring sessions
3. Run `php tao/scripts/taoUpdate.php` in order to add an extra column to the monitoring table
4. Run `php index.php '\oat\taoProctoring\scripts\tools\MonitoringExtraFieldConfigurationMigration'` to utilize the new column
5. Run `php index.php '\oat\taoProctoring\scripts\tools\MonitoringExtraFieldMigration' …
> Feature TR-3141 forward port delivery monitoring table merge

- manifest.php
- model/repository/MonitoringRepository.php
- chore: bump patch version in package manifest Kiryl Poyu 3 minutes ago
- refactor: remove unnecessary `isset` check, add empty value check in building of order statement 
- refactor: extract order to variables, move building numeric order statement method
- fix: ordering `authorized_by` field
- fix: trim for like search
- fix: cast json values to text for casting to decimal at numeric ordering
- fix:remove `strtolower` at in case-insensitive `stripos` usage
- fix: remove inserting `extra_data` field sorting by as query parameter
- fix: add type casting to `text` for `like` search condition in jsonb `extra_data_column`
- refactor: extract method from foreach body
- fix: fix not primary column sorting
> Backport TR-3297
